### ISSUE TITLE
Extended control build error with method marshal.size

### ISSUE THREAD

**Issue by herledant** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.450#1]
Hello Wagnerp,

I'm facing to error build with the .net 4.5 target network when i try to compil the extended Toolkit dll.

The error are on line 66,89, 199 and 201 on KryptonRichTextBoxExtended.cs file.

The error are : 

> Impossible to use method 'Marshal.Size(object)' non generic with arg of type Extended Controls
	
>  Impossible to use method 'Marshal.StructureToPtr(object, IntPtr, bool)' non generic with arg of type	Extended Controls.

![image](https://user-images.githubusercontent.com/9166449/44004434-fd8c0576-9e62-11e8-9ca7-08633e97edc8.png)

Many thankse for you help.

Best Regard's

**Comment by Wagnerp** [comment]
That's an odd bug, as it does work most of the time, but it sometimes it can throw up this error. I've never found out why this is.

**Comment by herledant** [comment]
May is possible that is due to the targeted famework?
It seems that's this error doesn't appear with 4.7 .net

**Comment by Wagnerp** [comment]
Maybe, if that's the case, I'll rip the code out. It might be that there was some API changes between 4.5 and 4.7.
